# Generated by Django 3.2 on 2022-01-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='company_colors',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='company_look',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='company_slogan',
        ),
        migrations.AddField(
            model_name='order',
            name='company_colors',
            field=models.CharField(default='Company Colours', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='company_description',
            field=models.CharField(default='Company Description', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='company_look',
            field=models.CharField(default='Company Look', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(default='Company Name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='company_slogan',
            field=models.CharField(default='Company Slogan', max_length=200),
        ),
    ]
